### ISSUE TITLE
this._getMedia() is undefined

### ISSUE THREAD

**Issue by JumBay** [miloproductionsinc/cordova-plugin-chromecast#9]
I still got the error mentioned on #8 with the latest version:
```js
Unhandled Promise rejection: – "undefined is not an object (evaluating 'this._getMedia().mediaSessionId = 'invalidated'')" – "; Zone:" – "<root>" – "; Task:" – "Promise.then" – "; Value:" (2)
TypeError: undefined is not an object (evaluating 'this._getMedia().mediaSessionId = 'invalidated'') — chrome.cast.js:893
"http://localhost:8100/plugins/cordova-plugin-chromecast/www/chrome.cast.js:893:21
http://localhost:8100/plugins/cordova-plugin-chromecast/www/chrome.cast.js:731:31
http://localhost:8100/plugins/cordova-plugin-chromecast/www/chrome.cast.js:1476:65
callbackFromNative@http://localhost:8100/cordova.js:295:63
http://localhost:8100/plugins/cordova-plugin-ionic-webview/src/www/ios/ios-wkwebview-exec.js:129:35
```

**Comment by Lindsay-Needs-Sleep** [comment]
If I am guessing right, you only get this error the first time you try to loadMedia?
If so I *think* I fixed it.  

I was only able to reproduce it once, every other time it worked. :/
So please let me know if this is still happening!  (And I might need more details about how to reproduce it.)

(Note: If you have cloned this repo, I did a history rewrite because of a mistake a couple commits ago, so you might need to delete your branch and re-pull.)

**Comment by JumBay** [comment]
I can confirm it now works perfectly. Great job

**Comment by Lindsay-Needs-Sleep** [comment]
Thank goodness!

Thanks for you help too!
